### ISSUE TITLE
USW Installer gets flagged by Windows Defender

### ISSUE THREAD

**Issue by TureBentzin** [Goddeh1/USW-Installer-App#1]
Seems like your Application gets flagged by Windows Defender now...
![grafik](https://user-images.githubusercontent.com/38729194/216154573-bc89dd8d-0617-4eae-96e8-7c224e237739.png) (its in german, but says the usual windows defender stuff)
https://www.virustotal.com/gui/file/e98e6f6d3cee45dcc0c9cbc51ab5a4faebc44e39da2912d10c0655ecda4850f6?nocache=1

**Comment by TureBentzin** [comment]
It says:

> Detected: Trojan...
> Status: Under Quarantine
>  little description on what Quarantine is 
> Details: This Programm is dangerous. It executes commands from an attacker.

**Comment by Goddeh1** [comment]
We're aware of this issue and are arranging to get a valid signature as well as a suitable certificate from Microsoft so that users do not encounter this issue in the future as we can confirm it is a false positive. Thanks for flagging this though!

If you have further enquiries, please contact us via the [TrixyBlox Discord](https://discord.gg/trixyblox)!
